### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by nickrager** [oliver006/elasticsearch-test-data#23]
When I am trying to upload data into a live cluster I am getting the following error:
RuntimeError: Cannot run the event loop while another loop is running

Please see attached doc for output.
[Python_Errors.txt](https://github.com/oliver006/elasticsearch-test-data/files/6037253/Python_Errors.txt)

**Comment by nickrager** [comment]
Duplicate of another issue.
Needs the correct version of tornado to work.

**Comment by oliver006** [comment]
🎉

**Comment by nickrager** [comment]
it might be prudent to change the readme to reflect the install from the requirements.txt
`pip3 install -r requirements.txt`
